### ISSUE TITLE
Proper Handling of Product Identifiers [21Dec2017-7]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/catalog-service#7]
Is it recommended to leave the "Product Identifier" given by NIMBLE instead of putting the one from the catalogue?

**Comment by wernher** [comment]
Product or object IDs are primary keys in any system. We must design for those keys to be preserved during the life-cycle within NIMBLE. This means: if the company needs reference to its catalogue numbers then NIMBLE must keep them as tuples so that it can hand references back: (NIMBLE-ID, CATALOGUE-X-ID,...).

**Comment by suatgonul** [comment]
@jinnerbichler I didn't get what you mean

**Comment by suatgonul** [comment]
Currently, we were using the (catalogue ID, manufacturers product ID) tuple to identify a catalogue line (product / service). It's of course possible to create a unique ID for each product as well.

**Comment by suatgonul** [comment]
The id discussed in this issue is the company-specific identifier, which is supposed to be provided by the company itself. So, closing this issue.
